language: shell
os: linux
dist: xenial
sudo: required
services:
  - docker

env:
  global:
    - PATH=/opt/python/3.7.1/bin:$PATH

addons:
  hosts:
    - localhost

before_install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.12.13/terraform_0.12.13_linux_amd64.zip" -o terraform.zip &> /dev/null
  - sudo unzip terraform.zip -d /opt/terraform &> /dev/null
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform &> /dev/null
  - rm -f terraform.zip &> /dev/null
  - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" &> /dev/null
  - python3 get-pip.py --user &> /dev/null
  - python3 -m pip install -Iv --user "botocore==1.17.36" &> /dev/null
  - python3 -m pip install -Iv --user "awscli==1.18.113" &> /dev/null
  - python3 -m pip install -Iv --user "awscli-local==0.7" &> /dev/null
  - sudo add-apt-repository -y ppa:swi-prolog/stable &> /dev/null
  - sudo apt-get update -y &> /dev/null
  - sudo apt-get install -y swi-prolog jq &> /dev/null
  
jobs:
  include:
    - stage: "test"
      script:
        - "docker build --tag prolamb/prolamb:latest -f build.Dockerfile ."
        - ./test.sh
        - ./test.readme.sh
    - stage: "deploy"
      script: 
        - "docker build --tag prolamb/prolamb:latest -f build.Dockerfile ."
        - ./deploy.sh
