language: sh

services:
  - docker
# install terraform

before_install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

jobs:
  include:
    - stage: "Tests"
      name: "Integration Tests"
      script: ./test.sh