language: sh
dist: xenial

services:
  - docker

env:
  global:
    - PATH=/opt/python/3.7.1/bin:$PATH

before_install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.12.13/terraform_0.12.13_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
  - python3 get-pip.py --user
  - python3 -m pip install --upgrade --user "awscli"
  - python3 -m pip install --upgrade --user "awscli-local"
  
jobs:
  include:
    - stage: "compile"
      script: "docker build --tag prolamb:latest -f build.Dockerfile ."
    - stage: "test"
      script: bash test.sh
    - stage: "deploy"
      script: bash deploy.sh

