language: sh
dist: bionic

python:
  - "3.8"

services:
  - docker
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
# install terraform

before_install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - docker pull lambci/lambda:build-provided
  - docker pull localstack/localstack:0.10.4
  - python3 -m pip install --user "awscli"
  - python3 -m pip install --user "awscli-local"

jobs:
  include:
    - stage: "Tests"
      name: "Integration Tests"
      script: bash test.sh